version: '3.2'

services:
  nginx:
    build:
      context: conf/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docroot:/var/www
    ports:
      - "127.0.0.1:${NGINX_PORT}:8080"
    depends_on:
      - php

  php:
    build:
      context: conf/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./docroot:/var/www
      - ./data:/data
    extra_hosts:
      - host.docker.internal:host-gateway

  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- ./:/usr/app
      - /srv/2TBb/gallery2/videosmall:/videos
    ports:
      - "0.0.0.0:8048:8048"
    entrypoint: [ "./runlive"]