FROM golang:1.17 AS downloader
WORKDIR /usr/app                       # not under /go
#COPY component-review-handler/ ./  # (double-check this COPY syntax)
#RUN go build -o downloader ./cmd/downloader

FROM node:14
# vvv add this line
#COPY --from=downloader /app/downloader /usr/local/bin/

# same as before
WORKDIR /usr/app
#COPY package*.json ./
#RUN npm install
#COPY . .
#ENV NODE_TLS_REJECT_UNAUTHORIZED='0'
#EXPOSE 3000

RUN apt-get update && apt-get install -y ffmpeg npm
RUN apt-get update && apt-get install -y golang


#RUN go install github.com/MaZderMind/live-hls-transcode@master
#RUN cd $GOPATH/src/github.com/MaZderMind/live-hls-transcode/

#RUN cd /usr/app
#RUN make dependencies
#RUN make

#COPY . .
#COPY test.js /usr/app/test.js


